name = "marked/hammer"
version = "0.2.0"
description = "A set of utilities for Jecs"
authors = ["marked"]
repository = "https://git.devmarked.win/marked/hammer"
license = "MIT"
includes = ["lib", "lib/**", "LICENSE", "pesde.toml", "README.md", "jecs.luau"]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
# `marked/jecs@0.5.5` was yanked due to some issues, this is the equivalent
jecs = { name = "marked/jecs_nightly", version = "=0.5.5-nightly.20250312T202956Z" }
