name = "mark_marks/jecs_utils"
version = "0.1.7-rc.1"
description = "A set of utilities for jecs"
authors = ["marked/Mark-Marks"]
repository = "https://github.com/mark-marks/jecs-utils"
license = "MIT"
includes = ["lib", "LICENSE", "pesde.toml", "README.md", "jecs.luau"]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
jecs = { name = "mark_marks/jecs_pesde", version = "^0.4.0" }
