# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
wally = "upliftgames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.5.1"
lune = "lune-org/lune@0.9.2"
selene = "kampfkarren/selene@0.28.0"
luau-lsp = "johnnymorganz/luau-lsp@1.45.0"
stylua = "johnnymorganz/stylua@2.1.0"
pesde = "daimond113/pesde@0.6.2+registry.0.2.2"
