[package]
name = "mark-marks/hammer"
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
    "default.project.json",
    "lib",
    "lib/**",
    "LICENSE",
    "wally.toml",
    "README.md",
]

[dependencies]
jecs = "ukendio/jecs@0.6.1"
