[package]
name = "mark-marks/jecs-utils"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
    "default.project.json",
    "dist",
    "dist/**",
    "LICENSE",
    "wally.toml",
    "README.md",
]

[dependencies]
jecs = "ukendio/jecs@0.3.0"
