name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    name: Build
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: https://github.com/CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.githubtoken }}

      - name: Build
        run: |
          lune run build

      - name: Upload Build Artifact
        uses: https://git.devmarked.win/actions/upload-artifact@v4
        with:
          name: build
          path: hammer.rbxm

  release:
    name: Release
    needs: [build]
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Download Build
        uses: https://git.devmarked.win/actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Create Release
        uses: actions/forgejo-release@v2.6
        with:
          direction: upload
          title: Hammer ${{ github.ref_name }}
          release-dir: build

  publish:
    name: Publish
    needs: [release]
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: https://github.com/CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.githubtoken }}

      - name: Wally Login
        run: wally login --token ${{ secrets.WALLY_AUTH_TOKEN }}

      - name: Wally Publish
        run: wally publish

      - name: Pesde Login
        run: pesde auth login --token "${{ secrets.PESDE_AUTH_TOKEN }}"

      - name: Pesde Publish
        run: pesde publish -y
